AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: AWS SAM template to deploy a Golang Lambda function connected to an AppSync GraphQL API.

Resources:
  ###############################################
  # TABLE
  ###############################################
  ItemsTable:
    Type: "AWS::Serverless::SimpleTable"
    Properties:
      TableName: "items"

  ###############################################
  # FUNCTIONS
  ###############################################
  CreateItemFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x # Indicates the build method for the function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: cmd/create-item
      Tracing: Active
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt CreateItemLambdaExecutionRole.Arn
      Environment:
        Variables:
          APPSYNC_API_ENDPOINT: !Ref GraphQLAPI
          TABLE_NAME: !Ref ItemsTable

  ReadItemFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x # Indicates the build method for the function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: cmd/read-item
      Tracing: Active
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
      Environment:
        Variables:
          APPSYNC_API_ENDPOINT: !Ref GraphQLAPI
          TABLE_NAME: !Ref ItemsTable

  ListItemsFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x # Indicates the build method for the function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: cmd/list-items
      Tracing: Active
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
      Environment:
        Variables:
          APPSYNC_API_ENDPOINT: !Ref GraphQLAPI
          TABLE_NAME: !Ref ItemsTable

  ListTagsFunction:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: go1.x # Indicates the build method for the function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: cmd/list-tags
      Tracing: Active
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
      Environment:
        Variables:
          APPSYNC_API_ENDPOINT: !Ref GraphQLAPI
          TABLE_NAME: !Ref ItemsTable

  ###############################################
  # APPSYNC API
  ###############################################
  GraphQLAPI:
    Type: "AWS::AppSync::GraphQLApi"
    Properties:
      Name: "GolangGraphQLAPI"
      AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncLoggingRole.Arn
        FieldLogLevel: ERROR
      XrayEnabled: true

  ###############################################
  # APPSYNC API KEY
  ###############################################
  GraphQLAPIKey:
    Type: "AWS::AppSync::ApiKey"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Expires: 1747877779 # Example expiration timestamp for the API key

  ###############################################
  # APPSYNC SCHEMA
  ###############################################
  GraphQLSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Definition: |
        input CreateItemInput {
          name: String!
        }

        type Item {
          id: ID!
          name: String!
          tags: [String]
        }

        type CreateItemPayload {
          item: Item!
        }

        type Query {
          item(id: ID!): Item
          items: [Item!]!
        }

        type Mutation {
          createItem(input: CreateItemInput!): CreateItemPayload!
        }

  ###############################################
  # APPSYNC DATA SOURCES
  ###############################################
  CreateItemLambdaDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Name: "CreateItemLambdaDataSource"
      Type: "AWS_LAMBDA"
      LambdaConfig:
        LambdaFunctionArn: !GetAtt CreateItemFunction.Arn
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

  ReadItemLambdaDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Name: "ReadItemLambdaDataSource"
      Type: "AWS_LAMBDA"
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ReadItemFunction.Arn
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

  ListItemsLambdaDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Name: "ListItemsLambdaDataSource"
      Type: "AWS_LAMBDA"
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ListItemsFunction.Arn
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

  ListTagsLambdaDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Name: "ListTagsLambdaDataSource"
      Type: "AWS_LAMBDA"
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ListTagsFunction.Arn
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

  ###############################################
  # APPSYNC DATA RESOLVERS
  ###############################################
  CreateItemResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      TypeName: "Mutation"
      FieldName: "createItem"
      DataSourceName: !GetAtt CreateItemLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "Invoke",
          "payload": {
            "args": $util.toJson($ctx.args)
          }
        }

  ReadItemResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      TypeName: "Query"
      FieldName: "item"
      DataSourceName: !GetAtt ReadItemLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "BatchInvoke",
          "payload": {
              "args": $util.toJson($ctx.args)
          }
        }
      ResponseMappingTemplate: |
        #if( $context.result && $context.result.error )
              $utils.error($context.result.error)
        #else
              $utils.toJson($context.result.value)
        #end

  ListItemsResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      TypeName: "Query"
      FieldName: "items"
      DataSourceName: !GetAtt ListItemsLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "BatchInvoke",
          "payload": {
            "args": $util.toJson($ctx.args)
          }
        }
      ResponseMappingTemplate: |
        #if( $context.result && $context.result.error )
              $utils.error($context.result.error)
        #else
              $utils.toJson($context.result.value)
        #end

  ListTagsResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      TypeName: "Item"
      FieldName: "tags"
      DataSourceName: !GetAtt ListTagsLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "BatchInvoke",
          "payload": {
            "args": $util.toJson($ctx.args)
          }
        }
      ResponseMappingTemplate: |
        #if( $context.result && $context.result.error )
              $utils.error($context.result.error)
        #else
              $utils.toJson($context.result.value)
        #end

  ###############################################
  # EXECUTION ROLES
  # TODO: limit resource
  ###############################################
  AppSyncLambdaServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "appsync.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AppSyncInvokeLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  CreateItemLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "DynamoDBAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource:
                  - !GetAtt "ItemsTable.Arn"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*

  AppSyncLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AppSyncLoggingPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*

Outputs:
  GraphQLAPIEndpoint:
    Value: !GetAtt GraphQLAPI.GraphQLUrl
    Description: "URL of the AppSync GraphQL API"
